trigger: none
pr: none

schedules:
  - cron: '0 0 * * *'
    displayName: Daily builds
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: ubuntu-latest
      os: linux
    sdl:
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        image: windows-2022
        os: windows
      credscan:
        enabled: true
      policheck:
        enabled: true
      binskim:
        enabled: true
    stages:
      - stage: Build
        jobs:
          - job: Build
            displayName: Build Python SDK
            steps:
              - checkout: self
                submodules: recursive

              - task: UsePythonVersion@0
                displayName: Set up Python
                inputs:
                  versionSpec: '3.12'

              - task: PipAuthenticate@1
                displayName: Authenticate with Azure Artifacts
                inputs:
                  artifactFeeds: "$(System.TeamProject)/GraphDeveloperExperiences_Public"
                  onlyAddExtraIndex: false

              - script: python -m pip install --upgrade pip
                displayName: Upgrade pip
                workingDirectory: $(Build.SourcesDirectory)

              - script: pip install -r requirements-dev.txt
                displayName: Install dependencies
                workingDirectory: $(Build.SourcesDirectory)
